### ISSUE TITLE
Slider doesn't work

### ISSUE THREAD

**Issue by jpvalery** [themexpert/switch#2]
[FIXED] 

Hey,

Slider configuration doesn't work. I've put the data for 3 different slides but they don't appear correctly in the website.
This seems to be a recurring issue from what I'm reading on your forums. And since no one seems to get a fix, I definitely don't want to spend 20$ for "support".

I do understand that this is a free theme and support isn't included. But nevertheless, it's not an excuse to ship a product that is not functionning as advertised.

Please explain how to get the sliders to display the correct data that I've input in the settings.

Thanks,

**Comment by codexpert** [comment]
If the slider is not working then we'll fix it, you don't have to pay for support. Let us investigate the issue. We've also plan to re-build switch with http://getonepager.com/ page builder :)

**Comment by themefisher** [comment]
The Demo site is also running with the same theme.If the problem is our end then the demo site should not appear ... Whatever let us check .. Thanks for you feedback.

**Comment by jpvalery** [comment]
Thanks,
Please see image attached for my settings and the final result on http://madkaijucartel.com.
I saved multiple times and emptied my cache. Yet, the text displayed is not the one from the settings :(
Thanks for your reactivity and help.
![redux theme option mad kaiju cartel wordpress 2015-09-20 12-07-53](https://cloud.githubusercontent.com/assets/4112343/9981640/56a04ee8-5f90-11e5-853e-560b67534a41.png)

**Comment by themefisher** [comment]
Hello  @jpvalery ,
Everything is ok.In every slider there is a overly , the overly color and your background image color is same thats why you did not notice the changes.your image http://madkaijucartel.com/wp-content/uploads/2015/09/madkaijucartel-bg.jpg shows properly and and it works .. 
<img width="1417" alt="screen shot 2015-09-20 at 10 50 04 pm" src="https://cloud.githubusercontent.com/assets/10640964/9981845/9b4ece7a-5fea-11e5-81ca-7067a9a928e6.png">
.So next suggestion is please upload another image and check is that works or not.
Thanks

**Comment by jpvalery** [comment]
except that it doesn't work on my side :(
See screenshots attached
![capture d ecran 2015-09-20 a 13 06 43](https://cloud.githubusercontent.com/assets/4112343/9981911/a6991ff8-5f98-11e5-9b97-b4ba88a0aeba.png)
![capture d ecran 2015-09-20 a 13 07 51](https://cloud.githubusercontent.com/assets/4112343/9981913/a69d0f32-5f98-11e5-9d7f-fd08d459247a.png)
![capture d ecran 2015-09-20 a 13 08 00](https://cloud.githubusercontent.com/assets/4112343/9981912/a69cd7a6-5f98-11e5-977f-ca75dc5957b0.png)

**Comment by themefisher** [comment]
In this case our theme is working well. So if you now need any help you have to buy our support pack. Thanks for your great collaboration mind.

**Comment by jpvalery** [comment]
How can you say it's okay when the text I've put in the settings is clearly not the one displayed ?

And how can I trust you to spend 20$ on a support pack when you clearly deny the issue presented here ???

**Comment by themefisher** [comment]
Better to buy a premium theme for your site or wait for the new version release of switch .. Thanks ...

**Comment by jpvalery** [comment]
Great state of mind "we're shipping a non-functionning theme, we don't want to help, so go see elsewhere".
Instead of converting me into a client, you're converting me into a detractor of your company.
Great job.

**Comment by codexpert** [comment]
@jpvalery I'm really sorry for any offensive language from @themefisher 
1. Switch is working fine on our end and others(read 50K install). 
2. @themefisher already gave you the fix.

---

We didn't shipped switch 'non-functional'. As your support required our time to investigate you need to pay for the support, simple as that.

**Comment by jpvalery** [comment]
I tried the fix given and it changed nothing. 
I didn't do anything custom. Just uploaded the zip file. Thus, if there's an issue, it's from this theme.
Thanks.

**Comment by mehedi-sharif** [comment]
Hello @jpvalery ,
We just released a simple update. If possible then download it from our repository. If it works that's otherwise let us know. 
Download Link: https://github.com/themexpert/switch/archive/master.zip
Thanks

**Comment by jpvalery** [comment]
Working fine now ! Thanks ! (y)
