### ISSUE TITLE
About Us Tab Not working

### ISSUE THREAD

**Issue by gavin-hardaker** [themexpert/switch#3]
Hi,

Do you guys have a solution to the about us portion of the theme not working?

**Comment by codexpert** [comment]
For instance remove this 2 lines

https://github.com/themexpert/switch/blob/master/sections/section-about.php#L5
and 
https://github.com/themexpert/switch/blob/master/sections/section-about.php#L68

We'll update the theme.

**Comment by gavin-hardaker** [comment]
Thank you very much!
